-- No-op migration.
--
-- The schema changes covered by the original generated file were already
-- introduced in:
--   - 0016_human_paid_consumption.sql
--   - 0017_content_types_domain_slug_unique.sql
--   - 0018_autonomous_agent_runs.sql
--   - 0019_unified_actor_identity.sql
--
-- Keeping 0020 as a no-op preserves journal ordering for databases that have
-- already stamped/applied up through 0019, while avoiding duplicate-object
-- failures on fresh CI databases.
