import {
    capabilityMatrix,
    dryRunCapabilities,
    requiredProtocolSurfaces,
    compatibilityProtocolSurfaces,
} from '../contracts/capability-matrix.js';
import {
    isExperimentalAgentRunsEnabled,
    isExperimentalDelegationEnabled,
    isExperimentalRevenueEnabled,
} from '../config/runtime-features.js';
import {
    getAssetSignedTtlSeconds,
    resolveAssetStorageProviderConfig,
    SUPPORTED_ASSET_DELIVERY_MODES,
    SUPPORTED_ASSET_UPLOAD_MODES,
    SUPPORTED_MCP_ASSET_UPLOAD_MODES,
} from '../config/assets.js';
import {
    getReactiveSubscriptionRecipe,
    SUPPORTED_REACTIVE_FILTER_FIELDS,
    SUPPORTED_REACTIVE_EVENT_TOPICS,
    SUPPORTED_REACTIVE_SUBSCRIPTION_RECIPES,
    WORDCLAW_EVENT_NOTIFICATION_METHOD,
} from '../mcp/reactive-events.js';

export type CapabilityManifest = ReturnType<typeof buildCapabilityManifest>;

const TRUE_VALUE = 'true';

function isAuthRequired() {
    return (process.env.AUTH_REQUIRED || TRUE_VALUE).toLowerCase() === TRUE_VALUE;
}

function isInsecureLocalAdminEnabled() {
    return process.env.NODE_ENV !== 'production'
        && (process.env.ALLOW_INSECURE_LOCAL_ADMIN || 'false').toLowerCase() === TRUE_VALUE;
}

export function buildCapabilityManifest() {
    const experimentalRevenue = isExperimentalRevenueEnabled();
    const experimentalDelegation = isExperimentalDelegationEnabled();
    const experimentalAgentRuns = isExperimentalAgentRunsEnabled();
    const authRequired = isAuthRequired();
    const insecureLocalAdminEnabled = isInsecureLocalAdminEnabled();
    const writeRequiresCredential = authRequired || !insecureLocalAdminEnabled;
    const recommendedActorProfile = authRequired
        ? 'api-key'
        : insecureLocalAdminEnabled
            ? 'anonymous-local-dev'
            : 'api-key';
    const vectorRagEnabled = Boolean(process.env.OPENAI_API_KEY);
    const vectorRagModel = vectorRagEnabled
        ? (process.env.OPENAI_EMBEDDING_MODEL || 'text-embedding-3-small')
        : null;
    const actorProfiles = [
        {
            id: 'public-discovery',
            label: 'Public discovery',
            actorType: 'system',
            authMode: 'none',
            availableSurfaces: ['rest'],
            actorIdExamples: [],
            recommendedFor: ['discover-deployment'],
            domainContext: {
                required: false,
                strategy: 'none',
                note: 'Use this unauthenticated profile only for deployment discovery via GET /api/capabilities.',
            },
            notes: [
                'No authentication is required.',
                'This profile is read-only and does not create a persisted actor identity.',
            ],
        },
        {
            id: 'api-key',
            label: 'Domain-scoped API key',
            actorType: 'api_key',
            authMode: 'api-key',
            availableSurfaces: ['rest', 'mcp-http'],
            actorIdExamples: ['api_key:12'],
            recommendedFor: ['bootstrap-workspace', 'discover-workspace', 'author-content', 'review-workflow', 'manage-integrations', 'consume-paid-content', 'verify-provenance'],
            domainContext: {
                required: true,
                strategy: 'implicit-from-key',
                note: 'The API key record fixes the active domain. Do not send x-wordclaw-domain for API-key requests.',
            },
            notes: [
                'Use x-api-key or Authorization: Bearer <api-key>.',
                'Prefer content:write for mutations and review tasks; content:read is sufficient for read-only paid-content access.',
            ],
        },
        {
            id: 'env-key',
            label: 'Environment-configured API key',
            actorType: 'env_key',
            authMode: 'api-key',
            availableSurfaces: ['rest', 'mcp-http'],
            actorIdExamples: ['env_key:remote-admin'],
            recommendedFor: ['bootstrap-workspace', 'discover-workspace', 'author-content', 'review-workflow', 'manage-integrations', 'consume-paid-content', 'verify-provenance'],
            domainContext: {
                required: true,
                strategy: 'server-configured-default',
                note: 'Environment-configured keys use the server default domain mapping. They are best suited for local or single-domain deployments.',
            },
            notes: [
                'Use x-api-key or Authorization: Bearer <api-key> with a key listed in API_KEYS.',
                'Prefer database-backed API keys for multi-tenant or production setups where the domain must be explicit per key.',
            ],
        },
        {
            id: 'supervisor-session',
            label: 'Supervisor session',
            actorType: 'supervisor',
            authMode: 'supervisor-session',
            availableSurfaces: ['rest', 'mcp-http'],
            actorIdExamples: ['supervisor:1'],
            recommendedFor: ['bootstrap-workspace', 'discover-workspace', 'review-workflow', 'manage-integrations', 'verify-provenance'],
            domainContext: {
                required: true,
                strategy: 'header',
                header: 'x-wordclaw-domain',
                note: 'Supervisor sessions must send the active domain on each request.',
            },
            notes: [
                'Use the supervisor_session cookie from operator login.',
                'Best suited for browser-attached MCP sessions or human-in-the-loop review flows.',
            ],
        },
        {
            id: 'mcp-local',
            label: 'Local MCP session',
            actorType: 'mcp',
            authMode: 'local-stdio',
            availableSurfaces: ['mcp-stdio'],
            actorIdExamples: ['mcp-local'],
            recommendedFor: ['discover-deployment', 'bootstrap-workspace', 'discover-workspace', 'author-content', 'review-workflow', 'manage-integrations', 'verify-provenance'],
            domainContext: {
                required: true,
                strategy: 'environment',
                environmentVariable: 'WORDCLAW_DOMAIN_ID',
                note: 'Local stdio MCP sessions derive the active domain from WORDCLAW_DOMAIN_ID.',
            },
            notes: [
                'Default for CLI-spawned local MCP sessions.',
                'Use remote HTTP MCP plus an API key when you need a shareable attachable agent session.',
            ],
        },
        {
            id: 'anonymous-local-dev',
            label: 'Insecure local admin fallback',
            actorType: 'anonymous',
            authMode: 'none',
            availableSurfaces: ['rest'],
            actorIdExamples: ['anonymous'],
            recommendedFor: [],
            developmentOnly: true,
            domainContext: {
                required: true,
                strategy: 'local-default',
                note: 'Only available when ALLOW_INSECURE_LOCAL_ADMIN=true; defaults to domain 1.',
            },
            notes: [
                'Development only. Do not depend on this profile for hosted or production agents.',
            ],
        },
    ];
    const contentLifecycleRecipe = getReactiveSubscriptionRecipe('content-lifecycle');
    const reviewDecisionsRecipe = getReactiveSubscriptionRecipe('review-decisions');
    const integrationAdminRecipe = getReactiveSubscriptionRecipe('integration-admin');
    const assetStorage = resolveAssetStorageProviderConfig();
    const agentGuidance = {
        routingHints: [
            {
                intent: 'discover-deployment',
                preferredSurface: 'rest',
                preferredActorProfile: 'public-discovery',
                fallbackSurface: 'mcp',
                rationale: 'The REST manifest is public and easiest to read before you authenticate or connect over MCP.',
            },
            {
                intent: 'bootstrap-workspace',
                preferredSurface: 'mcp',
                preferredActorProfile: 'mcp-local',
                fallbackSurface: 'rest',
                rationale: 'Bootstrap needs live readiness checks plus in-band domain creation, and local MCP remains usable even before the first domain exists.',
            },
            {
                intent: 'discover-workspace',
                preferredSurface: 'mcp',
                preferredActorProfile: 'api-key',
                fallbackSurface: 'rest',
                rationale: 'Once authenticated, the next question is which domain and content models are actually actionable for the current actor.',
            },
            {
                intent: 'author-content',
                preferredSurface: 'mcp',
                preferredActorProfile: 'api-key',
                fallbackSurface: 'rest',
                rationale: 'MCP is the most natural agent surface for schema discovery, dry-run validation, and content mutations.',
            },
            {
                intent: 'review-workflow',
                preferredSurface: 'mcp',
                preferredActorProfile: 'api-key',
                fallbackSurface: 'rest',
                rationale: 'Workflow review and comments fit agent-style tool calls well, while REST remains a direct fallback.',
            },
            {
                intent: 'manage-integrations',
                preferredSurface: 'mcp',
                preferredActorProfile: 'api-key',
                fallbackSurface: 'rest',
                rationale: 'API keys and webhooks are available on MCP and are simpler to automate as tool calls.',
            },
            {
                intent: 'consume-paid-content',
                preferredSurface: 'rest',
                preferredActorProfile: 'api-key',
                fallbackSurface: null,
                rationale: 'L402 settlement and entitlement-backed reads remain REST-first even though discovery is available elsewhere.',
            },
            {
                intent: 'verify-provenance',
                preferredSurface: 'mcp',
                preferredActorProfile: 'api-key',
                fallbackSurface: 'rest',
                rationale: 'Audit verification works well over MCP, while REST remains a direct fallback for filtered trail inspection.',
            },
        ],
        actorProfiles,
        taskRecipes: [
            {
                id: 'bootstrap-workspace',
                goal: 'Provision the first domain or verify bootstrap readiness before attempting schema and content writes.',
                preferredSurface: 'mcp',
                fallbackSurface: 'rest',
                recommendedAuth: 'api-key-or-local-mcp',
                preferredActorProfile: 'mcp-local',
                supportedActorProfiles: ['mcp-local', 'api-key', 'env-key', 'supervisor-session'],
                recommendedApiKeyScopes: ['admin'],
                requiredModules: ['content-runtime'],
                dryRunRecommended: false,
                steps: [
                    {
                        title: 'Read the live deployment status',
                        surface: 'rest',
                        operation: 'GET /api/deployment-status',
                        purpose: 'Confirm whether the runtime already has a provisioned domain and whether bootstrap is still required.',
                    },
                    {
                        title: 'Create the first domain in-band',
                        surface: 'mcp',
                        operation: 'create_domain',
                        purpose: 'Bootstrap the workspace from inside the agent session without dropping down to a raw REST call.',
                    },
                    {
                        title: 'Fallback to the REST bootstrap path when MCP is unavailable',
                        surface: 'rest',
                        operation: 'POST /api/domains',
                        purpose: 'Provision the first domain or an additional admin-managed domain over the HTTP API.',
                        optional: true,
                    },
                    {
                        title: 'Hand off to workspace discovery',
                        surface: 'mcp',
                        operation: 'guide_task bootstrap-workspace or guide_task discover-workspace',
                        purpose: 'Verify that bootstrap completed and then inspect the active workspace before creating schemas or content.',
                    },
                ],
            },
            {
                id: 'discover-deployment',
                goal: 'Determine which modules, transports, auth modes, and dry-run paths are enabled before acting.',
                preferredSurface: 'rest',
                fallbackSurface: 'mcp',
                recommendedAuth: 'none',
                preferredActorProfile: 'public-discovery',
                supportedActorProfiles: ['public-discovery', 'api-key', 'env-key', 'supervisor-session', 'mcp-local'],
                recommendedApiKeyScopes: [],
                requiredModules: [],
                dryRunRecommended: false,
                steps: [
                    {
                        title: 'Read the deployment manifest',
                        surface: 'rest',
                        operation: 'GET /api/capabilities',
                        purpose: 'Inspect enabled modules, auth expectations, protocol roles, and dry-run support.',
                    },
                    {
                        title: 'Read the live deployment status',
                        surface: 'rest',
                        operation: 'GET /api/deployment-status',
                        purpose: 'Confirm database connectivity, MCP transport health, and whether bootstrap, auth, or vector-RAG blockers still gate the next action.',
                    },
                    {
                        title: 'Escalate first-domain bootstrap when the install is still empty',
                        surface: 'mcp',
                        operation: 'guide_task bootstrap-workspace',
                        purpose: 'If deployment status reports zero domains, switch to the dedicated bootstrap recipe before attempting schema or content writes.',
                        optional: true,
                    },
                    {
                        title: 'Confirm the write actor after authenticating',
                        surface: 'rest',
                        operation: 'GET /api/identity',
                        purpose: 'If writes require credentials, verify the active domain and scope set before mutating runtime state.',
                    },
                    {
                        title: 'Mirror the manifest inside an MCP session',
                        surface: 'mcp',
                        operation: 'read system://capabilities',
                        purpose: 'Confirm the same contract after connecting as an MCP client.',
                        optional: true,
                    },
                    {
                        title: 'Check the in-band MCP deployment status',
                        surface: 'mcp',
                        operation: 'read system://deployment-status',
                        purpose: 'Verify the live readiness snapshot without leaving the MCP session.',
                        optional: true,
                    },
                ],
            },
            {
                id: 'discover-workspace',
                goal: 'Determine which domain and content models are available before choosing an authoring, review, workflow, or paid-content target.',
                preferredSurface: 'mcp',
                fallbackSurface: 'rest',
                recommendedAuth: 'api-key',
                preferredActorProfile: 'api-key',
                supportedActorProfiles: ['api-key', 'env-key', 'mcp-local', 'supervisor-session'],
                recommendedApiKeyScopes: ['content:read'],
                requiredModules: ['content-runtime'],
                dryRunRecommended: false,
                steps: [
                    {
                        title: 'Confirm the current actor and domain',
                        surface: 'rest',
                        operation: 'GET /api/identity',
                        purpose: 'Verify which domain and scope set the current credential is bound to before discovering content targets.',
                    },
                    {
                        title: 'Read the workspace context snapshot',
                        surface: 'rest',
                        operation: 'GET /api/workspace-context',
                        purpose: 'Inspect the current domain, accessible domains, and content model inventory for the active actor.',
                    },
                    {
                        title: 'Mirror the workspace inside MCP',
                        surface: 'mcp',
                        operation: 'read system://workspace-context',
                        purpose: 'Inspect the same workspace inventory without leaving the MCP session.',
                        optional: true,
                    },
                    {
                        title: 'Resolve the best target for the current task',
                        surface: 'mcp',
                        operation: 'resolve_workspace_target or read system://workspace-target/<intent>',
                        purpose: 'Skip manual ranking when the agent already knows it wants an authoring, review, workflow, or paid-content target.',
                        optional: true,
                    },
                ],
            },
            {
                id: 'author-content',
                goal: 'Design or select a schema, then create or update schema-bound content with validation, versioning, and optional dry-run checks.',
                preferredSurface: 'mcp',
                fallbackSurface: 'rest',
                recommendedAuth: 'api-key',
                preferredActorProfile: 'api-key',
                supportedActorProfiles: ['api-key', 'env-key', 'mcp-local', 'supervisor-session'],
                recommendedApiKeyScopes: ['content:write'],
                requiredModules: ['content-runtime'],
                dryRunRecommended: true,
                steps: [
                    {
                        title: 'Discover the target schema',
                        surface: 'mcp',
                        operation: 'list_content_types or get_content_type',
                        purpose: 'Find the content model and inspect its schema before generating data, or decide that a new schema must be designed first.',
                    },
                    {
                        title: 'Ask for schema design guidance when no target exists',
                        surface: 'mcp',
                        operation: 'guide_task { taskId: "author-content" }',
                        purpose: 'Get manifest-oriented schema patterns for memory, task-log, and checkpoint style content before creating a new model.',
                        optional: true,
                    },
                    {
                        title: 'Validate a draft without persisting it',
                        surface: 'mcp',
                        operation: 'create_content_item { dryRun: true } or update_content_item { dryRun: true }',
                        purpose: 'Use the runtime validator to catch schema and policy issues before write time.',
                    },
                    {
                        title: 'Persist or revise the content item',
                        surface: 'mcp',
                        operation: 'create_content_item or update_content_item',
                        purpose: 'Store the item after dry-run feedback is satisfactory.',
                    },
                    {
                        title: 'Inspect versions when revising',
                        surface: 'mcp',
                        operation: 'get_content_item_versions or rollback_content_item',
                        purpose: 'Review or revert history if the content needs correction.',
                        optional: true,
                    },
                ],
                reactiveFollowUp: {
                    purpose: 'Keep the active schema in sync after content creation, revision, rollback, and publication events.',
                    recipeId: contentLifecycleRecipe?.id ?? null,
                    topics: contentLifecycleRecipe?.topics ?? [],
                    recommendedFilters: ['contentTypeId'],
                    example: {
                        tool: 'subscribe_events',
                        arguments: {
                            recipeId: 'content-lifecycle',
                            filters: {
                                contentTypeId: '<resolved contentTypeId>',
                            },
                        },
                    },
                    note: 'Use guide_task author-content without contentTypeId to bootstrap schema design, then repeat it with contentTypeId once the target schema is known and reactive follow-up becomes actionable.',
                },
            },
            {
                id: 'review-workflow',
                goal: 'Move content through supervised review, comments, and decision steps.',
                preferredSurface: 'mcp',
                fallbackSurface: 'rest',
                recommendedAuth: 'api-key-or-supervisor',
                preferredActorProfile: 'api-key',
                supportedActorProfiles: ['api-key', 'env-key', 'supervisor-session', 'mcp-local'],
                recommendedApiKeyScopes: ['content:write'],
                requiredModules: ['content-runtime', 'workflow-review'],
                dryRunRecommended: false,
                steps: [
                    {
                        title: 'Create the workflow path if needed',
                        surface: 'mcp',
                        operation: 'create_workflow and create_workflow_transition',
                        purpose: 'Define the review path that content should follow.',
                        optional: true,
                    },
                    {
                        title: 'Submit content into review',
                        surface: 'mcp',
                        operation: 'submit_review_task',
                        purpose: 'Move a content item from its current state into supervised review.',
                    },
                    {
                        title: 'Add review feedback',
                        surface: 'mcp',
                        operation: 'add_review_comment',
                        purpose: 'Record actionable feedback for the current review cycle.',
                        optional: true,
                    },
                    {
                        title: 'Approve or reject the task',
                        surface: 'mcp',
                        operation: 'decide_review_task',
                        purpose: 'Complete the supervised review step and settle the item state.',
                    },
                ],
                reactiveFollowUp: {
                    purpose: 'Stay attached to approval and rejection outcomes while supervising or submitting review tasks.',
                    recipeId: reviewDecisionsRecipe?.id ?? null,
                    topics: reviewDecisionsRecipe?.topics ?? [],
                    recommendedFilters: ['reviewTaskId'],
                    example: {
                        tool: 'subscribe_events',
                        arguments: {
                            recipeId: 'review-decisions',
                            filters: {
                                reviewTaskId: '<current reviewTaskId>',
                            },
                        },
                    },
                    note: 'Use guide_task review-workflow when you want the runtime to narrow the filter set to the current actionable task.',
                },
            },
            {
                id: 'manage-integrations',
                goal: 'Provision agent credentials and outbound webhooks for external integrations.',
                preferredSurface: 'mcp',
                fallbackSurface: 'rest',
                recommendedAuth: 'api-key-or-supervisor',
                preferredActorProfile: 'api-key',
                supportedActorProfiles: ['api-key', 'env-key', 'supervisor-session', 'mcp-local'],
                recommendedApiKeyScopes: ['admin'],
                requiredModules: ['api-keys-webhooks'],
                dryRunRecommended: false,
                steps: [
                    {
                        title: 'Create an API key',
                        surface: 'mcp',
                        operation: 'create_api_key',
                        purpose: 'Provision a scoped credential for an external agent or integration.',
                    },
                    {
                        title: 'Register webhook delivery',
                        surface: 'mcp',
                        operation: 'create_webhook',
                        purpose: 'Subscribe an external system to audit or content-change events.',
                        optional: true,
                    },
                    {
                        title: 'Inspect or rotate integration state',
                        surface: 'mcp',
                        operation: 'list_api_keys, revoke_api_key, list_webhooks, update_webhook',
                        purpose: 'Manage lifecycle and rotation for integration surfaces.',
                        optional: true,
                    },
                ],
                reactiveFollowUp: {
                    purpose: 'Observe API key and webhook mutations while provisioning, rotating, or auditing integration surfaces.',
                    recipeId: integrationAdminRecipe?.id ?? null,
                    topics: integrationAdminRecipe?.topics ?? [],
                    recommendedFilters: [],
                    example: {
                        tool: 'subscribe_events',
                        arguments: {
                            recipeId: 'integration-admin',
                        },
                    },
                    note: 'This follow-up requires admin-grade scopes; guide_task manage-integrations will suppress it for weaker actors.',
                },
            },
            {
                id: 'consume-paid-content',
                goal: 'Purchase access to paid content and perform entitlement-backed reads.',
                preferredSurface: 'rest',
                fallbackSurface: null,
                recommendedAuth: 'api-key',
                preferredActorProfile: 'api-key',
                supportedActorProfiles: ['api-key', 'env-key'],
                recommendedApiKeyScopes: ['content:read'],
                requiredModules: ['payments-l402'],
                dryRunRecommended: false,
                steps: [
                    {
                        title: 'Discover offers for a content item',
                        surface: 'rest',
                        operation: 'GET /api/content-items/:id/offers',
                        purpose: 'Find the available paid-access offers for a content item.',
                    },
                    {
                        title: 'Start the L402 purchase',
                        surface: 'rest',
                        operation: 'POST /api/offers/:id/purchase',
                        purpose: 'Receive the Lightning challenge and purchase metadata.',
                    },
                    {
                        title: 'Confirm the payment',
                        surface: 'rest',
                        operation: 'POST /api/offers/:id/purchase/confirm',
                        purpose: 'Complete settlement and activate the entitlement.',
                    },
                    {
                        title: 'Read with the entitlement',
                        surface: 'rest',
                        operation: 'GET /api/content-items/:id with entitlement context',
                        purpose: 'Fetch the paid content through the entitlement-backed read path.',
                    },
                ],
            },
            {
                id: 'verify-provenance',
                goal: 'Verify which actor performed a recent action and inspect the corresponding audit trail.',
                preferredSurface: 'mcp',
                fallbackSurface: 'rest',
                recommendedAuth: 'api-key-or-supervisor',
                preferredActorProfile: 'api-key',
                supportedActorProfiles: ['api-key', 'env-key', 'supervisor-session', 'mcp-local'],
                recommendedApiKeyScopes: ['audit:read'],
                requiredModules: ['audit-trail'],
                dryRunRecommended: false,
                steps: [
                    {
                        title: 'Confirm the current actor snapshot',
                        surface: 'mcp',
                        operation: 'read system://current-actor',
                        purpose: 'Verify which canonical actor id and domain the current session is using.',
                    },
                    {
                        title: 'Inspect recent actor-attributed events',
                        surface: 'mcp',
                        operation: 'get_audit_logs or guide_task',
                        purpose: 'Review the most recent audit events tied to the current actor or a target entity.',
                    },
                    {
                        title: 'Fallback to filtered REST audit queries when needed',
                        surface: 'rest',
                        operation: 'GET /api/audit-logs?actorId=<actorId>&entityType=<type>&entityId=<id>',
                        purpose: 'Use the REST audit trail if a client needs cursor pagination or explicit URL-based queries.',
                        optional: true,
                    },
                ],
                reactiveFollowUp: {
                    purpose: 'Track actor- or entity-scoped audit activity without polling the trail for every provenance check.',
                    recipeId: null,
                    topics: ['audit.*'],
                    recommendedFilters: ['actorId', 'actorType', 'entityType', 'entityId', 'action'],
                    example: {
                        tool: 'subscribe_events',
                        arguments: {
                            topics: ['audit.*'],
                            filters: {
                                actorId: '<actorId>',
                                actorType: '<actorType>',
                                entityType: '<entityType>',
                                entityId: '<entityId>',
                                action: '<action>',
                            },
                        },
                    },
                    note: 'Use guide_task verify-provenance for a live recommendation that can upgrade this generic audit watch to a narrower recipe when the entity class is already known.',
                },
            },
        ],
    };

    return {
        generatedAt: new Date().toISOString(),
        product: {
            name: 'WordClaw',
            positioning: 'Safe content runtime for AI agents and human supervisors',
        },
        discovery: {
            restManifestPath: '/api/capabilities',
            restStatusPath: '/api/deployment-status',
            restIdentityPath: '/api/identity',
            restWorkspacePath: '/api/workspace-context',
            restWorkspaceTargetPath: '/api/workspace-target',
            mcpResourceUri: 'system://capabilities',
            mcpStatusResourceUri: 'system://deployment-status',
            mcpActorResourceUri: 'system://current-actor',
            mcpWorkspaceResourceUri: 'system://workspace-context',
            mcpWorkspaceTargetToolName: 'resolve_workspace_target',
            mcpReactiveToolName: 'subscribe_events',
            mcpReactiveNotificationMethod: WORDCLAW_EVENT_NOTIFICATION_METHOD,
            cliCommand: 'node dist/cli/index.js capabilities show',
            cliStatusCommand: 'node dist/cli/index.js capabilities status',
            cliWhoAmICommand: 'node dist/cli/index.js capabilities whoami',
            cliWorkspaceCommand: 'node dist/cli/index.js workspace guide',
            cliWorkspaceResolveCommand: 'node dist/cli/index.js workspace resolve --intent authoring',
        },
        protocolSurfaces: {
            rest: {
                role: 'primary',
                basePath: '/api',
            },
            mcp: {
                role: 'primary',
                transports: ['stdio', 'streamable-http'],
                endpoint: '/mcp',
                attachable: true,
                reactive: {
                    supported: true,
                    transport: 'streamable-http',
                    sessionHeader: 'mcp-session-id',
                    standaloneSsePath: '/mcp',
                    subscriptionTool: 'subscribe_events',
                    notificationMethod: WORDCLAW_EVENT_NOTIFICATION_METHOD,
                    supportedTopics: [...SUPPORTED_REACTIVE_EVENT_TOPICS],
                    supportedFilterFields: [...SUPPORTED_REACTIVE_FILTER_FIELDS],
                    subscriptionRecipes: SUPPORTED_REACTIVE_SUBSCRIPTION_RECIPES.map((recipe) => ({
                        id: recipe.id,
                        title: recipe.title,
                        description: recipe.description,
                        topics: [...recipe.topics],
                        requiredScopes: [...recipe.requiredScopes],
                    })),
                },
            },
            graphql: {
                role: 'compatibility',
            },
        },
        auth: {
            rest: {
                apiKeyHeader: 'x-api-key',
                bearerHeader: 'Authorization: Bearer <api-key>',
                supervisorCookie: 'supervisor_session',
            },
            mcp: {
                endpoint: '/mcp',
                apiKeyHeader: 'x-api-key',
                bearerHeader: 'Authorization: Bearer <api-key>',
                supervisorCookie: 'supervisor_session',
                supervisorHeader: 'x-wordclaw-domain',
            },
            domainContext: {
                supervisorHeader: 'x-wordclaw-domain',
                apiKeysAreDomainScoped: true,
                mcpDomainEnv: 'WORDCLAW_DOMAIN_ID',
            },
            effective: {
                authRequired,
                writeRequiresCredential,
                insecureLocalAdminEnabled,
                recommendedActorProfile,
                recommendedScopes: ['content:write'],
                note: authRequired
                    ? 'Authenticated writes require an API key or supervisor session with the appropriate scope set.'
                    : insecureLocalAdminEnabled
                        ? 'Local unauthenticated writes are allowed only because ALLOW_INSECURE_LOCAL_ADMIN=true in a non-production environment.'
                        : 'Read-only discovery can be unauthenticated, but writes still require a credential because insecure local admin is not enabled.',
            },
        },
        bootstrap: {
            contentWritesRequireDomain: true,
            supportsInBandDomainCreation: true,
            restCreateDomainPath: '/api/domains',
            mcpCreateDomainTool: 'create_domain',
            recommendedGuideTask: 'bootstrap-workspace',
            noDomainErrorCode: 'NO_DOMAIN',
            note: 'Read deployment status before the first write, then use guide_task("bootstrap-workspace") to create the first domain when the install is still empty.',
        },
        vectorRag: {
            enabled: vectorRagEnabled,
            model: vectorRagModel,
            requiredEnvironmentVariables: ['OPENAI_API_KEY'],
            restPath: '/api/search/semantic',
            mcpTool: 'search_semantic_knowledge',
            note: vectorRagEnabled
                ? `Semantic search is enabled with embedding model ${vectorRagModel}.`
                : 'Semantic search is disabled until OPENAI_API_KEY is configured.',
        },
        toolEquivalence: [
            {
                intent: 'inspect-deployment',
                rest: 'GET /api/deployment-status',
                mcp: 'read system://deployment-status',
                graphql: null,
                cli: 'node dist/cli/index.js capabilities status',
            },
            {
                intent: 'create-domain',
                rest: 'POST /api/domains',
                mcp: 'create_domain',
                graphql: null,
                cli: 'node dist/cli/index.js domains create --name <value> --hostname <value>',
            },
            {
                intent: 'discover-workspace',
                rest: 'GET /api/workspace-target',
                mcp: 'resolve_workspace_target',
                graphql: null,
                cli: 'node dist/cli/index.js workspace resolve --intent authoring',
            },
            {
                intent: 'create-content-type',
                rest: 'POST /api/content-types',
                mcp: 'create_content_type',
                graphql: 'mutation createContentType',
                cli: 'node dist/cli/index.js content-types create --name <value> --slug <value> --schema-file <path>',
            },
            {
                intent: 'create-content-item',
                rest: 'POST /api/content-items',
                mcp: 'create_content_item',
                graphql: 'mutation createContentItem',
                cli: 'node dist/cli/index.js content create --content-type-id <id> --data-file <path>',
            },
        ],
        modules: [
            {
                id: 'content-runtime',
                tier: 'core',
                enabled: true,
                description: 'Schema-bound content type and content item operations, including field-aware queries and grouped projections.',
            },
            {
                id: 'asset-storage',
                tier: 'core',
                enabled: true,
                description: 'Schema-aware media asset storage, metadata, and delivery guidance.',
            },
            {
                id: 'workflow-review',
                tier: 'core',
                enabled: true,
                description: 'Supervisor review tasks, comments, and workflow transitions.',
            },
            {
                id: 'form-runtime',
                tier: 'core',
                enabled: true,
                description: 'Reusable public form definitions built on content types, validation, workflows, and optional L402/payment enforcement.',
            },
            {
                id: 'api-keys-webhooks',
                tier: 'core',
                enabled: true,
                description: 'Agent-facing credential management and webhook registration.',
            },
            {
                id: 'background-jobs',
                tier: 'core',
                enabled: true,
                description: 'Generic scheduled and deferred background jobs for webhook fan-out, scheduled status changes, and future side effects.',
            },
            {
                id: 'payments-l402',
                tier: 'core',
                enabled: true,
                description: 'Paid content, offers, payments, and entitlement-backed reads.',
            },
            {
                id: 'audit-trail',
                tier: 'core',
                enabled: true,
                description: 'Canonical actor-attributed audit history for verification and post-action provenance checks.',
            },
            {
                id: 'revenue-reporting',
                tier: 'experimental',
                enabled: experimentalRevenue,
                description: 'Earnings and payout-oriented surfaces remain incubating.',
            },
            {
                id: 'delegation',
                tier: 'experimental',
                enabled: experimentalDelegation,
                description: 'Entitlement delegation remains an incubating module.',
            },
            {
                id: 'agent-runs',
                tier: 'experimental',
                enabled: experimentalAgentRuns,
                description: 'Autonomous run orchestration remains an incubating module.',
            },
        ],
        contentRuntime: {
            enabled: true,
            globals: {
                supported: true,
                model: 'singleton-content-type',
                restListPath: '/api/globals',
                restItemPath: '/api/globals/:slug',
                graphqlListField: 'globals',
                graphqlItemField: 'global',
                graphqlMutation: 'updateGlobal',
                mcpListTool: 'list_globals',
                mcpGetTool: 'get_global',
                mcpUpdateTool: 'update_global',
                cliListCommand: 'node dist/cli/index.js globals list',
                cliGetCommand: 'node dist/cli/index.js globals get --slug <slug>',
                cliUpdateCommand: 'node dist/cli/index.js globals update --slug <slug> --data-file <path>',
                note: 'Globals are first-class singleton content types. The schema stays in content-types; the document state is read and written through the dedicated globals surface.',
            },
            workingCopyPreview: {
                supported: true,
                publicationStates: ['draft', 'published', 'changed'],
                readQueryFlag: 'draft',
                previewTokenPaths: ['/api/content-items/:id/preview-token', '/api/globals/:slug/preview-token'],
                previewReadPaths: ['/api/preview/content-items/:id', '/api/preview/globals/:slug'],
                graphqlFields: ['contentItems', 'contentItem', 'globals', 'global'],
                mcpTools: ['get_content_items', 'get_content_item', 'list_globals', 'get_global'],
                cliCommands: [
                    'node dist/cli/index.js content get --id <id> --published',
                    'node dist/cli/index.js content preview-token --id <id>',
                    'node dist/cli/index.js globals get --slug <slug> --published',
                    'node dist/cli/index.js globals preview-token --slug <slug>',
                ],
                note: 'Content reads expose the current working copy by default and can prefer the latest published snapshot with draft=false/--published. Preview tokens are short-lived, domain-scoped, and limited to one content item or global.',
            },
            semanticIndexReadiness: {
                supported: true,
                deploymentRestPath: '/api/deployment-status',
                deploymentMcpResource: 'system://deployment-status',
                contentRestPaths: ['/api/content-items', '/api/content-items/:id', '/api/globals', '/api/globals/:slug'],
                graphqlFields: ['contentItems', 'contentItem', 'globals', 'global'],
                mcpTools: ['get_content_items', 'get_content_item', 'list_globals', 'get_global'],
                note: 'Deployment status reports runtime embedding health and queue state, while content reads expose both embeddingReadiness and persisted sync metadata (embeddingStatus, embeddingChunks, embeddingUpdatedAt, embeddingErrorCode) for each item or global.',
            },
            localization: {
                supported: true,
                schemaExtension: 'x-wordclaw-localization',
                localizedFieldFlag: 'x-wordclaw-localized',
                readQueryFlags: ['draft', 'locale', 'fallbackLocale'],
                restPaths: ['/api/content-items', '/api/content-items/:id', '/api/globals', '/api/globals/:slug'],
                graphqlFields: ['contentItems', 'contentItem', 'globals', 'global'],
                mcpTools: ['get_content_items', 'get_content_item', 'list_globals', 'get_global'],
                cliCommands: [
                    'node dist/cli/index.js content list --locale <locale>',
                    'node dist/cli/index.js content get --id <id> --locale <locale>',
                    'node dist/cli/index.js globals list --locale <locale>',
                    'node dist/cli/index.js globals get --slug <slug> --locale <locale>',
                ],
                note: 'Localized fields are stored as canonical locale maps and can be resolved at read time with locale and fallbackLocale across all core read surfaces.',
            },
            reverseReferences: {
                supported: true,
                restPaths: ['/api/content-items/:id/used-by', '/api/assets/:id/used-by'],
                graphqlFields: ['contentItemUsedBy', 'assetUsedBy'],
                mcpTools: ['get_content_item_usage', 'get_asset_usage'],
                cliCommands: [
                    'node dist/cli/index.js content used-by --id <id>',
                    'node dist/cli/index.js assets used-by --id <id>',
                ],
                note: 'Reverse-reference usage graphs are derived on demand from current items plus stored historical versions, which makes impact analysis available without maintaining a separate projection table.',
            },
            generatedArtifacts: {
                supported: true,
                sourceSurfaces: ['content-types schema', 'capability manifest'],
                cliCommand: 'node dist/cli/index.js schema generate --out <path>',
                outputFiles: ['runtime.ts', 'types.ts', 'validators.ts', 'client.ts', 'index.ts'],
                note: 'The CLI can generate typed TypeScript/Zod/runtime client artifacts directly from the live content-model and capability surfaces.',
            },
            forms: {
                supported: true,
                adminRestPaths: ['/api/forms', '/api/forms/:id'],
                publicRestPaths: ['/api/public/forms/:slug', '/api/public/forms/:slug/submissions'],
                graphqlFields: ['forms', 'form', 'createForm', 'updateForm', 'deleteForm'],
                mcpTools: ['list_forms', 'get_form', 'create_form', 'update_form', 'delete_form', 'submit_form'],
                cliCommands: [
                    'node dist/cli/index.js forms list',
                    'node dist/cli/index.js forms get --id <id>',
                    'node dist/cli/index.js forms create --name <value> --slug <value> --content-type-id <id> --fields-file <path>',
                    'node dist/cli/index.js forms submit --slug <slug> --domain-id <id> --data-file <path>',
                ],
                workflowIntegration: true,
                paymentIntegration: true,
                backgroundFollowUps: true,
                note: 'Forms are first-class bounded intake definitions that validate into content items, can auto-submit into review, can challenge with L402 when enabled, and can trigger job-backed follow-up webhooks.',
            },
            fieldAwareQueries: {
                supported: true,
                requiresContentTypeId: true,
                queryableFieldKinds: ['string', 'number', 'boolean'],
                filterOperators: ['eq', 'contains', 'gte', 'lte'],
                sortModes: ['field', 'updatedAt', 'createdAt', 'version'],
                restPath: '/api/content-items',
                mcpTool: 'get_content_items',
                graphqlField: 'contentItems',
                cliCommand: 'node dist/cli/index.js content list --content-type-id <id> --field-name <field> --field-value <value>',
            },
            projections: {
                supported: true,
                requiresContentTypeId: true,
                groupByMode: 'single-field',
                groupableFieldKinds: ['string', 'number', 'boolean'],
                metrics: ['count', 'sum', 'avg', 'min', 'max'],
                numericMetricsRequireNumericField: true,
                restPath: '/api/content-items/projections',
                mcpTool: 'project_content_items',
                graphqlField: 'contentItemProjection',
                cliCommand: 'node dist/cli/index.js content project --content-type-id <id> --group-by <field>',
                note: 'Grouped projections provide lightweight leaderboard and analytics-style read models without requiring background materialization.',
            },
            publicWriteLane: {
                supported: true,
                requiresSchemaPolicy: true,
                issueTokenPath: '/api/content-types/:id/public-write-tokens',
                createPath: '/api/public/content-types/:id/items',
                updatePath: '/api/public/content-items/:id',
                tokenHeader: 'x-public-write-token',
                authorizationScheme: 'Bearer <public-write-token>',
                subjectBindingMode: 'single-subject-field',
                allowedOperations: ['create', 'update'],
                note: 'Public write lanes are TTL-bound, content-type-scoped session/player tokens for app-owned draft/session mutations without exposing a full API key to the client.',
            },
            lifecycle: {
                supported: true,
                requiresSchemaPolicy: true,
                triggerMode: 'lazy-on-touch',
                schemaExtension: 'x-wordclaw-lifecycle',
                defaultClock: 'updatedAt',
                defaultArchiveStatus: 'archived',
                restListPath: '/api/content-items',
                restProjectionPath: '/api/content-items/projections',
                mcpListTool: 'get_content_items',
                mcpProjectionTool: 'project_content_items',
                graphqlListField: 'contentItems',
                graphqlProjectionField: 'contentItemProjection',
                includeArchivedFlag: 'includeArchived',
                note: 'Lifecycle-managed content auto-archives on read/list/projection touch once its schema TTL elapses, while operators can opt back into archived rows explicitly.',
            },
        },
        backgroundJobs: {
            enabled: true,
            restPaths: ['/api/jobs', '/api/jobs/:id', '/api/jobs/worker-status', '/api/content-items/:id/schedule-status'],
            graphqlFields: ['jobs', 'job', 'jobsWorkerStatus', 'createJob', 'cancelJob', 'scheduleContentStatusChange'],
            mcpTools: ['list_jobs', 'get_job', 'create_job', 'cancel_job', 'schedule_content_status_change'],
            cliCommands: [
                'node dist/cli/index.js jobs list',
                'node dist/cli/index.js jobs get --id <id>',
                'node dist/cli/index.js jobs create --kind <kind> --payload-file <path>',
                'node dist/cli/index.js jobs cancel --id <id>',
                'node dist/cli/index.js jobs schedule-status --id <id> --status <value> --run-at <iso>',
            ],
            workerStatusPath: '/api/jobs/worker-status',
            supportedKinds: ['content_status_transition', 'outbound_webhook'],
            note: 'Background jobs provide a small generic queue for scheduled status transitions, webhook fan-out and retries, form follow-up actions, and future plugin-managed tasks.',
        },
        paidContent: {
            l402Enabled: true,
            purchaseFlowSurface: 'rest',
            entitlementReadSurface: 'rest',
            note: 'MCP is suitable for discovery and management; paid-content settlement and entitlement reads remain REST-first.',
        },
        assetStorage: {
            enabled: true,
            configuredProvider: assetStorage.configuredProvider,
            effectiveProvider: assetStorage.effectiveProvider,
            fallbackApplied: assetStorage.fallbackApplied,
            supportedProviders: [...assetStorage.supportedProviders],
            upload: {
                rest: {
                    path: '/api/assets',
                    modes: [...SUPPORTED_ASSET_UPLOAD_MODES],
                    directProviderUpload: {
                        enabled: assetStorage.effectiveProvider === 's3',
                        issuePath: '/api/assets/direct-upload',
                        completePath: '/api/assets/direct-upload/complete',
                        method: 'PUT',
                        providers: ['s3'],
                    },
                },
                mcp: {
                    tool: 'create_asset',
                    modes: [...SUPPORTED_MCP_ASSET_UPLOAD_MODES],
                },
            },
            delivery: {
                supportedModes: [...SUPPORTED_ASSET_DELIVERY_MODES],
                public: {
                    contentPath: '/api/assets/:id/content',
                },
                signed: {
                    contentPath: '/api/assets/:id/content',
                    issuePath: '/api/assets/:id/access',
                    issueTool: 'issue_asset_access',
                    defaultTtlSeconds: getAssetSignedTtlSeconds(),
                },
                entitled: {
                    contentPath: '/api/assets/:id/content',
                    offersPath: '/api/assets/:id/offers',
                },
            },
            lifecycle: {
                softDelete: true,
                restore: true,
                purge: true,
            },
            derivatives: {
                supported: true,
                createViaRestPath: '/api/assets',
                createViaMcpTool: 'create_asset',
                listPath: '/api/assets/:id/derivatives',
                listTool: 'list_asset_derivatives',
                sourceField: 'sourceAssetId',
                variantKeyField: 'variantKey',
                transformSpecField: 'transformSpec',
                note: 'Derivatives are first-class asset records linked back to a source asset and inherit the same lifecycle, audit, and storage rules.',
            },
        },
        agentGuidance,
        capabilities: capabilityMatrix.map((capability) => ({
            id: capability.id,
            description: capability.description,
            rest: capability.rest,
            mcp: capability.mcp,
            graphql: capability.graphql ?? null,
            dryRun: dryRunCapabilities.has(capability.id),
        })),
        protocolContract: {
            required: [...requiredProtocolSurfaces],
            compatibility: [...compatibilityProtocolSurfaces],
        },
        limitations: [
            'graphql_compatibility_only',
        ],
    };
}
